/* Generated By:JJTree: Do not edit this line. ASLActionNode.java */

package parser.asl;

public class ASLActionNode extends SimpleNode {
	public String clone;
	public String classname;
	public String urldir;
	
  public ASLActionNode(int id) {
    super(id);
  }

  public ASLActionNode(ASL p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ASLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
