/* Generated By:JJTree&JavaCC: Do not edit this line. ASLConstants.java */
package parser.asl;

public interface ASLConstants {

  int EOF = 0;
  int DEFINITION = 6;
  int SCRIPTID = 7;
  int AUTHOR = 8;
  int DATE = 9;
  int COMMENT = 10;
  int OBSERVATIONS = 11;
  int EXECUTE = 12;
  int MIGRATE = 13;
  int TO = 14;
  int TRACE = 15;
  int CLONE = 16;
  int RUN = 17;
  int FROM = 18;
  int SLEEP = 19;
  int REPORTNOW = 20;
  int REPORTCALLBACK = 21;
  int REPORTMAIL = 22;
  int SMTP = 23;
  int REPORTFINAL = 24;
  int OUTPUTCALLBACK = 25;
  int OUTPUT = 26;
  int DECIMAL_LITERAL = 27;
  int CHARACTER_LITERAL = 28;
  int DATE_LITERAL = 29;
  int STRING_LITERAL = 30;
  int IDENTIFIER = 31;
  int LETTER = 32;
  int DIGIT = 33;
  int LPAREN = 34;
  int RPAREN = 35;
  int LBRACE = 36;
  int RBRACE = 37;
  int LBRACKET = 38;
  int RBRACKET = 39;
  int SEMICOLON = 40;
  int COMMA = 41;
  int DOT = 42;
  int AT = 43;
  int CLASSNAME = 44;
  int HOSTNAME = 45;
  int EMAIL = 46;
  int URLDIR = 47;
  int MSECONDS = 48;
  int IP_ADDRESS = 49;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"definition\"",
    "\"scriptID\"",
    "\"author\"",
    "\"date\"",
    "\"comment\"",
    "\"obs\"",
    "\"execute\"",
    "\"migrate\"",
    "\"to\"",
    "\"trace\"",
    "\"clone\"",
    "\"run\"",
    "\"from\"",
    "\"sleep\"",
    "\"reportnow\"",
    "\"reportcallback\"",
    "\"reportmail\"",
    "\"smtp\"",
    "\"reportfinal\"",
    "\"outputcallback\"",
    "\"output\"",
    "<DECIMAL_LITERAL>",
    "<CHARACTER_LITERAL>",
    "<DATE_LITERAL>",
    "<STRING_LITERAL>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"@\"",
    "<CLASSNAME>",
    "<HOSTNAME>",
    "<EMAIL>",
    "<URLDIR>",
    "<MSECONDS>",
    "<IP_ADDRESS>",
    "\":\"",
  };

}
