/* Generated By:JJTree: Do not edit this line. ASLInputNode.java */

package parser.asl;

public class ASLInputNode extends SimpleNode {
  public ASLInputNode(int id) {
    super(id);
  }

  public ASLInputNode(ASL p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ASLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
