/* Generated By:JJTree: Do not edit this line. ASLMigrateNode.java */

package parser.asl;

public class ASLMigrateNode extends SimpleNode {
	public String ipAddress;
	public String trace;

  public ASLMigrateNode(int id) {
    super(id);
  }

  public ASLMigrateNode(ASL p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ASLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
