/* Generated By:JJTree: Do not edit this line. ASLStartNode.java */

package parser.asl;

public class ASLStartNode extends SimpleNode {
  public ASLStartNode(int id) {
    super(id);
  }

  public ASLStartNode(ASL p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ASLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
