/* Generated By:JJTree: Do not edit this line. /home/rs/workspace/esod/src/parser/asl/ASLTreeConstants.java */

package parser.asl;

public interface ASLTreeConstants
{
  public int JJTSTARTNODE = 0;
  public int JJTAGENTDEFINITIONNODE = 1;
  public int JJTEXECNODE = 2;
  public int JJTMIGRATENODE = 3;
  public int JJTACTIONNODE = 4;
  public int JJTREPORTNODE = 5;
  public int JJTOUTPUTNODE = 6;
  public int JJTPARAMSNODE = 7;
  public int JJTVOID = 8;
  public int JJTINPUTNODE = 9;


  public String[] jjtNodeName = {
    "StartNode",
    "AgentDefinitionNode",
    "ExecNode",
    "MigrateNode",
    "ActionNode",
    "ReportNode",
    "OutputNode",
    "ParamsNode",
    "void",
    "InputNode",
  };
}
