// Skeleton class generated by rmic, do not edit.
// Contents subject to change without notice.

package server;

public final class AgentHostImpl_Skel
    implements java.rmi.server.Skeleton
{
    private static final java.rmi.server.Operation[] operations = {
	new java.rmi.server.Operation("void accept(server.agent.Agent)"),
	new java.rmi.server.Operation("java.lang.String getHostname()"),
	new java.rmi.server.Operation("void moveTo(server.agent.Agent, java.lang.String)")
    };
    
    private static final long interfaceHash = 8764454517359933156L;
    
    public java.rmi.server.Operation[] getOperations() {
	return (java.rmi.server.Operation[]) operations.clone();
    }
    
    public void dispatch(java.rmi.Remote obj, java.rmi.server.RemoteCall call, int opnum, long hash)
	throws java.lang.Exception
    {
	if (opnum < 0) {
	    if (hash == 8291560071740420981L) {
		opnum = 0;
	    } else if (hash == 1650924292415669172L) {
		opnum = 1;
	    } else if (hash == 14017333758308150L) {
		opnum = 2;
	    } else {
		throw new java.rmi.UnmarshalException("invalid method hash");
	    }
	} else {
	    if (hash != interfaceHash)
		throw new java.rmi.server.SkeletonMismatchException("interface hash mismatch");
	}
	
	server.AgentHostImpl server = (server.AgentHostImpl) obj;
	switch (opnum) {
	case 0: // accept(Agent)
	{
	    server.agent.Agent $param_Agent_1;
	    try {
		java.io.ObjectInput in = call.getInputStream();
		$param_Agent_1 = (server.agent.Agent) in.readObject();
	    } catch (java.io.IOException e) {
		throw new java.rmi.UnmarshalException("error unmarshalling arguments", e);
	    } catch (java.lang.ClassNotFoundException e) {
		throw new java.rmi.UnmarshalException("error unmarshalling arguments", e);
	    } finally {
		call.releaseInputStream();
	    }
	    server.accept($param_Agent_1);
	    try {
		call.getResultStream(true);
	    } catch (java.io.IOException e) {
		throw new java.rmi.MarshalException("error marshalling return", e);
	    }
	    break;
	}
	    
	case 1: // getHostname()
	{
	    call.releaseInputStream();
	    java.lang.String $result = server.getHostname();
	    try {
		java.io.ObjectOutput out = call.getResultStream(true);
		out.writeObject($result);
	    } catch (java.io.IOException e) {
		throw new java.rmi.MarshalException("error marshalling return", e);
	    }
	    break;
	}
	    
	case 2: // moveTo(Agent, String)
	{
	    server.agent.Agent $param_Agent_1;
	    java.lang.String $param_String_2;
	    try {
		java.io.ObjectInput in = call.getInputStream();
		$param_Agent_1 = (server.agent.Agent) in.readObject();
		$param_String_2 = (java.lang.String) in.readObject();
	    } catch (java.io.IOException e) {
		throw new java.rmi.UnmarshalException("error unmarshalling arguments", e);
	    } catch (java.lang.ClassNotFoundException e) {
		throw new java.rmi.UnmarshalException("error unmarshalling arguments", e);
	    } finally {
		call.releaseInputStream();
	    }
	    server.moveTo($param_Agent_1, $param_String_2);
	    try {
		call.getResultStream(true);
	    } catch (java.io.IOException e) {
		throw new java.rmi.MarshalException("error marshalling return", e);
	    }
	    break;
	}
	    
	default:
	    throw new java.rmi.UnmarshalException("invalid method number");
	}
    }
}
