// Stub class generated by rmic, do not edit.
// Contents subject to change without notice.

package server;

public final class AgentHostImpl_Stub
    extends java.rmi.server.RemoteStub
    implements server.AgentHost, java.rmi.Remote
{
    private static final long serialVersionUID = 2;
    
    private static java.lang.reflect.Method $method_accept_0;
    private static java.lang.reflect.Method $method_getHostname_1;
    private static java.lang.reflect.Method $method_moveTo_2;
    
    static {
	try {
	    $method_accept_0 = server.AgentHost.class.getMethod("accept", new java.lang.Class[] {server.agent.Agent.class});
	    $method_getHostname_1 = server.AgentHost.class.getMethod("getHostname", new java.lang.Class[] {});
	    $method_moveTo_2 = server.AgentHost.class.getMethod("moveTo", new java.lang.Class[] {server.agent.Agent.class, java.lang.String.class});
	} catch (java.lang.NoSuchMethodException e) {
	    throw new java.lang.NoSuchMethodError(
		"stub class initialization failed");
	}
    }
    
    // constructors
    public AgentHostImpl_Stub(java.rmi.server.RemoteRef ref) {
	super(ref);
    }
    
    // methods from remote interfaces
    
    // implementation of accept(Agent)
    public void accept(server.agent.Agent $param_Agent_1)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_accept_0, new java.lang.Object[] {$param_Agent_1}, 8291560071740420981L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of getHostname()
    public java.lang.String getHostname()
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_getHostname_1, null, 1650924292415669172L);
	    return ((java.lang.String) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of moveTo(Agent, String)
    public void moveTo(server.agent.Agent $param_Agent_1, java.lang.String $param_String_2)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_moveTo_2, new java.lang.Object[] {$param_Agent_1, $param_String_2}, 14017333758308150L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
}
