/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class server_tasks_JNIGetEnvPathTask */

#ifndef _Included_server_tasks_JNIGetEnvPathTask
#define _Included_server_tasks_JNIGetEnvPathTask
#ifdef __cplusplus
extern "C" {
#endif
#undef server_tasks_JNIGetEnvPathTask_serialVersionUID
#define server_tasks_JNIGetEnvPathTask_serialVersionUID -9031466777376797219i64
/*
 * Class:     server_tasks_JNIGetEnvPathTask
 * Method:    getpath
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_server_tasks_JNIGetEnvPathTask_getpath
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
