/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class server_tasks_UnameJNITask */

#ifndef _Included_server_tasks_UnameJNITask
#define _Included_server_tasks_UnameJNITask
#ifdef __cplusplus
extern "C" {
#endif
#undef server_tasks_UnameJNITask_serialVersionUID
#define server_tasks_UnameJNITask_serialVersionUID -9031466777376797219LL
/*
 * Class:     server_tasks_UnameJNITask
 * Method:    jniuname
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_server_tasks_UnameJNITask_jniuname
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
