package corba;


/**
* corba/_CorbaFrontEndStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from CorbaFrontEnd.idl
* Tuesday, November 29, 2005 9:54:21 PM WET
*/

public class _CorbaFrontEndStub extends org.omg.CORBA.portable.ObjectImpl implements corba.CorbaFrontEnd
{

  public boolean validateScript (String script) throws corba.CorbaFrontEndPackage.RemoteError
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("validateScript", true);
                $out.write_string (script);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:corba/CorbaFrontEnd/RemoteError:1.0"))
                    throw corba.CorbaFrontEndPackage.RemoteErrorHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return validateScript (script        );
            } finally {
                _releaseReply ($in);
            }
  } // validateScript

  public void startAgent (String script)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("startAgent", false);
                $out.write_string (script);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                startAgent (script        );
            } finally {
                _releaseReply ($in);
            }
  } // startAgent

  public void listActiveAgents () throws corba.CorbaFrontEndPackage.RemoteError
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("listActiveAgents", true);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:corba/CorbaFrontEnd/RemoteError:1.0"))
                    throw corba.CorbaFrontEndPackage.RemoteErrorHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                listActiveAgents (        );
            } finally {
                _releaseReply ($in);
            }
  } // listActiveAgents

  public void listAvailableReports () throws corba.CorbaFrontEndPackage.RemoteError
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("listAvailableReports", true);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:corba/CorbaFrontEnd/RemoteError:1.0"))
                    throw corba.CorbaFrontEndPackage.RemoteErrorHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                listAvailableReports (        );
            } finally {
                _releaseReply ($in);
            }
  } // listAvailableReports

  public String getAgentReport (int idx) throws corba.CorbaFrontEndPackage.RemoteError
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getAgentReport", true);
                $out.write_long (idx);
                $in = _invoke ($out);
                String $result = $in.read_string ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:corba/CorbaFrontEnd/RemoteError:1.0"))
                    throw corba.CorbaFrontEndPackage.RemoteErrorHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getAgentReport (idx        );
            } finally {
                _releaseReply ($in);
            }
  } // getAgentReport

  public String getHostReport (int idx) throws corba.CorbaFrontEndPackage.RemoteError
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getHostReport", true);
                $out.write_long (idx);
                $in = _invoke ($out);
                String $result = $in.read_string ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:corba/CorbaFrontEnd/RemoteError:1.0"))
                    throw corba.CorbaFrontEndPackage.RemoteErrorHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getHostReport (idx        );
            } finally {
                _releaseReply ($in);
            }
  } // getHostReport

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:corba/CorbaFrontEnd:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.Object obj = org.omg.CORBA.ORB.init (args, props).string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     String str = org.omg.CORBA.ORB.init (args, props).object_to_string (this);
     s.writeUTF (str);
  }
} // class _CorbaFrontEndStub
