package corba;


/**
* corba/CorbaFrontEnd.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from CorbaFrontEnd.idl
* Tuesday, December 13, 2005 3:15:42 AM WET
*/

public interface CorbaFrontEnd extends CorbaFrontEndOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface CorbaFrontEnd
