package corba;


/**
* corba/CorbaFrontEnd.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from CorbaFrontEnd.idl
* Wednesday, December 14, 2005 10:15:17 PM WET
*/

public interface CorbaFrontEnd extends CorbaFrontEndOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface CorbaFrontEnd
