package corba;

/**
* corba/CorbaFrontEndHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from CorbaFrontEnd.idl
* Tuesday, November 29, 2005 9:54:21 PM WET
*/

public final class CorbaFrontEndHolder implements org.omg.CORBA.portable.Streamable
{
  public corba.CorbaFrontEnd value = null;

  public CorbaFrontEndHolder ()
  {
  }

  public CorbaFrontEndHolder (corba.CorbaFrontEnd initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = corba.CorbaFrontEndHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    corba.CorbaFrontEndHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return corba.CorbaFrontEndHelper.type ();
  }

}
