package corba;

/**
* corba/CorbaReportReceiverHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from CorbaFrontEnd.idl
* Friday, December 16, 2005 6:04:05 AM WET
*/

public final class CorbaReportReceiverHolder implements org.omg.CORBA.portable.Streamable
{
  public corba.CorbaReportReceiver value = null;

  public CorbaReportReceiverHolder ()
  {
  }

  public CorbaReportReceiverHolder (corba.CorbaReportReceiver initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = corba.CorbaReportReceiverHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    corba.CorbaReportReceiverHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return corba.CorbaReportReceiverHelper.type ();
  }

}
