package corba;


/**
* corba/CorbaFrontEndOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from CorbaFrontEnd.idl
* Friday, December 16, 2005 6:04:05 AM WET
*/

public interface CorbaFrontEndOperations 
{
  void register (corba.CorbaReportReceiver crr);
  void unregister (corba.CorbaReportReceiver crr);
  boolean helloPlatform ();
  boolean validateScript (String script) throws corba.CorbaFrontEndPackage.RemoteError;
  void startAgent (String script);
  String listActiveAgents () throws corba.CorbaFrontEndPackage.RemoteError;
  String listAvailableReports () throws corba.CorbaFrontEndPackage.RemoteError;
  String getAgentReport (int idx) throws corba.CorbaFrontEndPackage.RemoteError;
  void shutdown ();
} // interface CorbaFrontEndOperations
