package corba;


/**
* corba/CorbaFrontEndOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from CorbaFrontEnd.idl
* Thursday, December 15, 2005 2:22:22 AM WET
*/

public interface CorbaFrontEndOperations 
{
  boolean helloPlatform ();
  boolean validateScript (String script) throws corba.CorbaFrontEndPackage.RemoteError;
  void startAgent (String script);
  String listActiveAgents () throws corba.CorbaFrontEndPackage.RemoteError;
  String listAvailableReports () throws corba.CorbaFrontEndPackage.RemoteError;
  String getAgentReport (int idx) throws corba.CorbaFrontEndPackage.RemoteError;
  String getHostReport (int idx) throws corba.CorbaFrontEndPackage.RemoteError;
} // interface CorbaFrontEndOperations
