package corba;


/**
* corba/CorbaReportReceiverOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from CorbaFrontEnd.idl
* Friday, December 16, 2005 6:04:05 AM WET
*/

public interface CorbaReportReceiverOperations 
{
  void handleReport (String report);
} // interface CorbaReportReceiverOperations
