package corba;


/**
* corba/CorbaFrontEnd.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from CorbaFrontEnd.idl
* Friday, December 16, 2005 6:04:05 AM WET
*/

public interface CorbaFrontEnd extends CorbaFrontEndOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface CorbaFrontEnd
